USE ROLE AIRFLOW_ROLE;
USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_DB;

TRUNCATE TABLE RETAIL_DB.RAW.SALESDATA_INBOUND;

DROP TABLE IF EXISTS RETAIL_DB.STAGING.STG_VENTES;
DROP TABLE IF EXISTS RETAIL_DB.STAGING.MY_FIRST_DBT_MODEL;
